### ISSUE TITLE
Window decoration is affected by blur

### ISSUE THREAD

**Issue by null-von-sushi** [kupiqu/SierraBreezeEnhanced#24] opened 2019-03-05 23:59 UTC
Setting the corner radius to something extreme like 20 will show that the transparent region is affected by blur (it obviously should not be). The normal Breeze decorations do not have this issue.
![screenshot_20190305_235842](https://user-images.githubusercontent.com/13616397/53845879-ac54c800-3fa2-11e9-9213-f495e1852a4f.png)

**Comment by kupiqu** [comment] 2019-03-06 00:14
Mmm, I don't recall setting anything specific about the blur effect...

I don't think there's a setting for the corner radius in upstream Breeze
decorations. How did you adjust it?

**Comment by null-von-sushi** [comment] 2019-03-06 01:26
Using the Sierra Breeze Enhanced settings? I hope I didn't find the wrong project with the same name haha. 
![screenshot_20190306_012519](https://user-images.githubusercontent.com/13616397/53849136-c399b280-3fae-11e9-92db-0603de3058c3.png)

**Comment by kupiqu** [comment] 2019-03-06 07:02
Oh, I see. I thought you were taliking about official Breeze...

No wrong project ;)


--

Enviat des del telèfon

**Comment by Luwx** [comment] 2019-03-11 04:46
Upstream bug: https://bugs.kde.org/show_bug.cgi?id=395725

**Comment by null-von-sushi** [comment] 2019-03-11 16:03
But isn't S.B.E based on (Breeze Enhanced which is based on) Breeze? AFAIK Breeze is not aurorae but it's own custom thing. I may be wrong here though.

**Comment by kupiqu** [comment] 2019-03-11 16:11
You're right, SBE is a fork of BE, which itself is a fork of Breeze.

**Comment by ciampolo** [comment] 2019-03-13 05:19
This is caused by shadows ( see https://github.com/ishovkun/SierraBreeze/issues/8 ). I can confirm that disabling shadows fixes this.

**Comment by kupiqu** [comment] 2019-03-13 13:44
Interesting. I wonder if there is an easy way to modify shadows behavior
and fix this properly

Missatge de ciampolo <notifications@github.com> del dia dc., 13 de març
2019 a les 6:19:

**Comment by null-von-sushi** [comment] 2019-03-13 13:49
Not sure if I am misunderstanding this, but I disabled shadows and it's still blurred
![Screenshot_20190313_134859](https://user-images.githubusercontent.com/13616397/54283890-dad03580-4596-11e9-8cdc-c3b6bddf7876.png)

**Comment by kupiqu** [comment] 2019-03-13 14:51
it seems to be sth different.

(unfortunately I cannot test it myself for now. unfortunately my computer
died and a new one is on the way. i'll need a couple of weeks to get back
on track...)

Missatge de null <notifications@github.com> del dia dc., 13 de març 2019 a
les 9:51:

**Comment by ciampolo** [comment] 2019-03-19 01:47
Applying this effect  ( https://github.com/alex47/KDE-Rounded-Corners ) and commenting out the shadow drawing part fixes the issue.

**Comment by null-von-sushi** [comment] 2019-03-19 15:38
I have the shapecorners effect active (since that has a package on the AUR and I can manage that with my package manager). I will see if that has a shadow part and if it does try to uncomment that.

My problem with the KDE-Rounded-Corners repo is that they don't even mention [what it does differently to shapecorners](https://github.com/alex47/KDE-Rounded-Corners/issues/4)

**Comment by null-von-sushi** [comment] 2019-03-19 16:06
For what it's worth, commenting out line 256 and 257
```
data.quads = qds.select(KWin::WindowQuadShadow);
KWin::effects->paintWindow(w, mask, region, data);
``` 

in shapecorners does not fix it for me. Not sure if that is even the right line to comment out, but it did have a comment saying 'paint the shadow' above it. I also don't know if KDE-Rounded-Corners does anything differently.

**Comment by Luwx** [comment] 2019-03-19 18:49
If you don't use the opacity setting you could disable blur in breeze.json before compiling. That bug affects all the decorations that use blur, since kdecoration does not support masking out the corners.

**Comment by null-von-sushi** [comment] 2019-03-19 21:44
Holy crap it works. I wonder if the blur toggle could be added as a configurable option, that way people could just turn it off without having to recompile. Still, even without having to set a value in a json file is not that complicated.

**Comment by kupiqu** [comment] 2019-03-20 20:50
> I wonder if the blur toggle could be added as a configurable option

I'll try to check this out when I find some time, hopefully soon...

**Comment by ciampolo** [comment] 2019-03-21 02:09
> but it did have a comment saying 'paint the shadow' above it. I also don't know if KDE-Rounded-Corners does anything differently.

I commented out the mentioned lines in KDE-Rounded-Corners and the blurred corners went away.

Kwin draws a transparent area where the shadows are supposed to be. If you enable blur Kwin blurs the shadow area since that area is transparent. This is why applications that draw their own headerbars (ie CSD/Gnome apps) don't have this issue.

**Comment by Luwx** [comment] 2019-06-20 21:23
I looked around the blur effect code and apparently it treats the blur region separately for the decoration area(https://github.com/KDE/kwin/blob/e8fe3f2fb7195fe562a073d1a78eb05d74670cfd/effects/blur/blur.cpp#L389-L413). So, a hacky fix to [395725](https://bugs.kde.org/show_bug.cgi?id=395725) would be to patch the effect and then call the blur directly from the breeze deco, with a custom region based on the corner radius settings.

But even without the patch, this could be a nice feature for those who want blurred windows with rounded corners: 

![Screenshot_20190620_054908](https://user-images.githubusercontent.com/33076480/59882326-4b51d400-9388-11e9-8e47-809049fc78fa.png)

**Comment by kupiqu** [comment] 2019-06-21 13:38
I don't totally follow. Is it fixed now in Breeze?

**Comment by kupiqu** [comment] 2019-07-14 12:23
Adding a hack seems complicated. Let's hope KDE properly fixes this soon, and then I will port the fix to Sierra Breeze Enhanced right away.

**Comment by kupiqu** [comment] 2019-11-19 08:30
Closing as it is an upstream bug

**Closed by kupiqu** 2019-11-19 08:30 UTC
Labels: bug, upstream
