### ISSUE TITLE
Rounded border on maximized window

### ISSUE THREAD

**Issue by gabelluardo** [kupiqu/SierraBreezeEnhanced#104] opened 2022-02-21 20:25 UTC
On maximized window, rounded title bar border show the background

This is an example with 20px border radius: 

![immagine](https://user-images.githubusercontent.com/42920247/155020664-907eb711-fe70-4f86-8321-e9e9865d574c.png)

with the default breeza this doesn't happen:

![immagine](https://user-images.githubusercontent.com/42920247/155021614-5a30dfd5-796c-4efc-ad8a-5e75314a911e.png)

I think it sets the radius to 0px on maximized windows

**Comment by kupiqu** [comment] 2022-06-23 06:03
This is (perhaps was) a KDE bug, most likely fixed with #107, closing now.

**Closed by kupiqu** 2022-06-23 06:03 UTC

**Comment by gabelluardo** [comment] 2022-11-05 23:53
This seems to have reappeared with plasma 5.26

**Comment by kupiqu** [comment] 2022-11-06 09:00
Not sure what you mean exactly. Do you mean when the titlebar is not present on maximization? 

If so, please note that SBE here is intended to work different than Breeze as it keeps the borders. Just removing the titlebar including borders looks ugly (personal opinion), and round corners are consistent to this, SBE only removes the titlebar, but keeps all the rest: borders, outline, corners and shadows

**Comment by gabelluardo** [comment] 2022-11-06 15:48
I mean the title bar is rounded even on maximization 
![immagine](https://user-images.githubusercontent.com/42920247/200180378-54e41e28-44ed-4c8b-84c0-0c28ff10fa50.png)
![immagine](https://user-images.githubusercontent.com/42920247/200180455-0bef156b-60a4-4188-b2f0-938ee92adb4c.png)

**Comment by kupiqu** [comment] 2022-11-06 18:07
If I understand you correctly, this is the intended behavior

**Comment by Syndrizzle** [comment] 2022-12-01 07:15
> If I understand you correctly, this is the intended behavior

would it be possible to make this optional?

**Comment by kupiqu** [comment] 2022-12-01 07:30
I may consider revising a pull request... 

but I am still confused about what you are exactly asking for. What is the behavior of maximized windows that you would prefer in terms of [titlebar (on/off), rounded corners (on/off), outline (on/off) and shadows (on/off)]?

**Comment by Syndrizzle** [comment] 2022-12-01 17:27
I want that sierrabreezeenhanced disables rounded corners for maximized window

**Comment by kupiqu** [comment] 2022-12-01 17:51
I may revise a PR if you convince me of why should regular users bother about roundered corners appearing in maximized windows in contrast to others.

**Comment by Syndrizzle** [comment] 2022-12-02 03:42
It looks weird on no gaps, imagine seeing some space in the corner of your screen when your app is Maximized, even windows 11 doesn't keep them round...

**Comment by kupiqu** [comment] 2022-12-02 07:30
Fair enough. I use (1px) gaps and small (3 px) rounded corners, with no titlebar on maximized windows and it looks good.
If you (or sb else) wants to work on this and submit a PR, I will revise it.

**Comment by Syndrizzle** [comment] 2022-12-02 15:19
Only if I knew how to write C++ :(

**Comment by gabelluardo** [comment] 2022-12-05 12:30
If you give me any suggestions on where to start, I can work on it

**Comment by Syndrizzle** [comment] 2022-12-06 13:49
I am sorry, but I don't know about anything coming to my mind. I tried my best and I guess you can take a look at https://github.com/a-parhom/LightlyShaders/blob/c8e6b15abbb9918313fd1f76d040dd7e9380eed2/lightlyshaders.cpp#L222. That KDE rounded corners tool, it has 2 branches, the code is from main branch. Unfortunately, the main branch only works on plasma 5.25 and smaller, but refuses to compile on 5.26… the second branch works on 5.26, but relies on decorations like SierraBreezeEnhanced to provide the corners for it…. But since the main branch includes the toggle to disable for maximized window, it is possible to take a look at it.
