### ISSUE TITLE
[Feature Request] Add LIM support.

### ISSUE THREAD

**Issue by baduhai** [kupiqu/SierraBreezeEnhanced#95] opened 2021-08-07 12:49 UTC
It'd be nice to have LIM support as is available on Zren's [material-decoration](https://github.com/Zren/material-decoration/tree/master/src).

**Comment by baduhai** [comment] 2021-08-19 14:52
Preliminary suppor for LIM has been added to breeze on this [repo](https://invent.kde.org/agrinev/breeze/-/tree/lim/kdecoration).

**Comment by CavaleriOmar** [comment] 2021-08-30 08:59
> Il supporto preliminare per LIM è stato aggiunto a brezza su questo [repository ](https://invent.kde.org/agrinev/breeze/-/tree/lim/kdecoration).

Does this mean that you can already use LIM with SierraBreezeEnhanced?

**Comment by kupiqu** [comment] 2021-11-01 09:17
The repo is not actively maintained anymore. Pull requests welcome

**Comment by kupiqu** [comment] 2021-11-01 09:31
duplicate of #79

**Closed by kupiqu** 2021-11-01 09:31 UTC
Labels: duplicate
