### ISSUE TITLE
Make the Left aligned Title placement follow the horizontal button offset

### ISSUE THREAD

**Issue by ryu-ketsueki** [kupiqu/SierraBreezeEnhanced#84] opened 2021-01-02 19:39 UTC
Title on left alignment is too close to the edge. Perhaps it would be a good idea to make it follow the horizontal button offset
![Spectacle_20210102_163733](https://user-images.githubusercontent.com/39316730/103465310-02b6fd00-4d19-11eb-9d85-3f6d2bc67343.png)

**Comment by kupiqu** [comment] 2021-01-03 08:30
Is this a bug in SBE wrt Breeze or a feature request?

**Comment by ryu-ketsueki** [comment] 2021-01-08 14:15
It seems to be a bug, yeah. I also observed that the title only takes that space when there are no buttons on the left but the titlebar only updates the part that did respect the horizontal offset, with the rest staying there until the window loses focus
![Flameshot_202101 5_131032](https://user-images.githubusercontent.com/39316730/104024950-aafa1500-51a2-11eb-9292-c3a7c8f427c0.png)
![Flameshot_202101 5_131056](https://user-images.githubusercontent.com/39316730/104024951-ac2b4200-51a2-11eb-9ee4-576016f424d5.png)

**Comment by kupiqu** [comment] 2021-01-08 22:16
Could you elaborate a little bit? I don't understand if this is a bug in SBE or Breeze (although I suppose it's SBE) and not sure either what these screenshots show. I don't use Discord myself so not sure what to expect.

**Comment by ryu-ketsueki** [comment] 2021-01-08 22:30
The first one shows the name of a Direct Message Group (PS Screenshots). Later, I clicked to open an actual Direct Message with a friend in the list. Discord shows the At symbol then the username. That means that when the titlebar updates to show that it's a direct message with a friend, it didn't update for the area that was supposed to be free as indicated by the P still showing up when it updates to @JeanCA. This seem to be happening with the default breeze as well, now that you mention it. I should probably open a bug report with them as well. But while Breeze doesn't have the horizontal offset option, SBE does and it could be used for the Left aligned titlebar title as well, that way the padding can be adjusted to match the one of the buttons on the right

**Comment by kupiqu** [comment] 2021-01-10 09:37
So, if I understand this correctly there are two issues actually here (correct me if wrong):

- The titlebar does not get updated properly (upstream issue). 
Please report that to kde... If you open another issue here and link to the bug in kde, I can track how this issue evolves and if fixed in kde, I can incorporate that to SBE.

- In absence of buttons, the offset on the left is not the same that the offset on the right (SBE issue)
Could you paste a couple of screenshots showing the different behavior of this, left vs right?

**Comment by ryu-ketsueki** [comment] 2021-01-10 13:38
I will report it to KDE, don't worry. I kinda stumbled it after I opened this issue here on SBE
![Flameshot_20210110_103159](https://user-images.githubusercontent.com/39316730/104124390-6c459580-532f-11eb-8112-45e2dc7080fe.png)
![Flameshot_20210110_103223](https://user-images.githubusercontent.com/39316730/104124392-6cde2c00-532f-11eb-9788-40cb4a8a58f7.png)
![Flameshot_20210110_103312](https://user-images.githubusercontent.com/39316730/104124393-6cde2c00-532f-11eb-92fd-4eccdce3e275.png)
![Flameshot_20210110_103344](https://user-images.githubusercontent.com/39316730/104124394-6d76c280-532f-11eb-815d-11b804c76c27.png)
As for the second issue, basically the title is too far on the left, not respecting the horizontal offset feature of SBE. Not really an issue with buttons on the left, only being a bit too close to the buttons but that's just a spacing nitpicking. And the last screenshot shows that the same happens if the title alignment is on the right with no buttons on the right.

**Comment by kupiqu** [comment] 2021-01-10 15:28
Ok, I see, the issue is (mainly) about the behavior without buttons.

- if buttons are not present, the offset should apply to them? I guess so
- if buttons are present, the separation should be reasonable, perhaps a bit larger than currently, but I would need to know if current one is smaller than that of breeze. Could you please check?

**Comment by ryu-ketsueki** [comment] 2021-01-11 15:20
This is Breeze: 
![Flameshot_20210111_121642](https://user-images.githubusercontent.com/39316730/104200102-0298ba80-5407-11eb-895e-9690cbf23ba7.png)
And this is SBE:
![Flameshot_20210111_121659](https://user-images.githubusercontent.com/39316730/104200107-03315100-5407-11eb-9a85-582ba13fba3c.png)
I think Breeze's own spacing is consistent with what they are trying to do, yeah. I noticed that when the window decoration changed from Breeze to SBE, the spacing between the title and the button shortened a bit but was only clear when I was directly overving it. Comparing screenshots doesn't make it very clear.

**Comment by kupiqu** [comment] 2021-02-28 07:32
@ryu-ketsueki I think the issue is about the offset in absence of buttons. I think it won't be hard to fix. Would you give it a try and submit a pull request?

**Comment by kupiqu** [comment] 2021-04-09 13:59
I'll set this as a low priority bug for now, maybe somebody picks it up.

**Comment by kupiqu** [comment] 2021-11-01 09:27
My aim is that SBE is maintained by the community. This shouldn't be hard to fix. I hope someone in the community cares about SBE and submits a pull request about it... I could help if somebody wants to try but is lost where to start.

**Closed** 2022-09-01 10:18 UTC
Labels: bug
