### ISSUE TITLE
The inner-border of macStyle button look weird.

### ISSUE THREAD

**Issue by trmdi** [kupiqu/SierraBreezeEnhanced#40] opened 2019-11-27 15:21 UTC
See the difference between SierraBreezeEnhanced (above) and McMojave buttons (below):

![image](https://user-images.githubusercontent.com/11857205/69735692-b8ea0380-1163-11ea-8f1e-aa0f9816a9f9.png)

I think the lighter color border of buttons don't look very nice. Could you remove those border?

**Comment by kupiqu** [comment] 2019-11-27 15:43
Mmm, I'm not sure. I quite like them as is (it's very soft effect in my opinion). This was requested in #23. I guess making everyone happy is difficult...

Also, please note that titlebars can come in any color, not just light and dark gray backgrounds, and the outlines aim to enhance the contrast in all conditions (not saying it's perfect, but it's certainly better than without).

Also, there are so many options already. I don't think it makes much sense to add any further option unless strictly necessary.

**Comment by trmdi** [comment] 2019-11-27 15:49
Hmm, the idea looks good:
![pic](https://camo.githubusercontent.com/e3e68f43d0ec7f0e8fbfb4d57b2b65aa767a635b/68747470733a2f2f692e616c6c746865706963732e6e65742f6472696262622d312e706e67)
This uses a darken color while you choose the lighter one. Could you improve this a bit?

**Comment by kupiqu** [comment] 2019-11-27 15:56
Well, the darker works in light backgrounds, and the lighter in dark backgrounds.

The idea is to increase contrast, darkening on dark backgrounds doesn't work for that purpose.

**Comment by kupiqu** [comment] 2019-11-27 16:01
Also, I had to increase how much dark it looks because a soft darken was not enough for light colors different than grayish:

![image](https://user-images.githubusercontent.com/3875196/69738995-ef446600-1104-11ea-9b79-bfa63a78cc92.png)

![image](https://user-images.githubusercontent.com/3875196/69739162-37fc1f00-1105-11ea-90ba-466bfeb87f05.png)


![image](https://user-images.githubusercontent.com/3875196/69739131-2c105d00-1105-11ea-8334-c95de06d0220.png)

**Comment by kupiqu** [comment] 2019-11-27 16:04
On the light side:

![image](https://user-images.githubusercontent.com/3875196/69739388-a4771e00-1105-11ea-949a-651f9b7e3e55.png)

**Comment by kupiqu** [comment] 2019-11-27 16:05
I test this with the script that colors titlebar based on icon colors. I'm then interested in this border looking fairly good in all conditions, which is very tricky

**Comment by trmdi** [comment] 2019-11-27 16:45
Here are some comparison with macOS buttons:
It seems the contrast between the outline and the button color is very low, while your contrast is a bit too high ?

![image](https://user-images.githubusercontent.com/11857205/69741978-93aec280-116e-11ea-94d4-87442b6acc33.png)
![image](https://user-images.githubusercontent.com/11857205/69742244-0750cf80-116f-11ea-8827-2122ec07fc62.png)

Source screenshot: [light mode](https://i.redd.it/7fbkqkd368231.png), [dark mode](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/macos/Catalina/macos-catalina-system-prefs-general-dark-mode.jpg)

**Comment by kupiqu** [comment] 2019-11-27 18:15
Yes, perhaps, but as I said one would need to look at those when background color is not in grayscale.

One thing however that I may test is reducing pen's width. That is clearly different, and perhaps a thinner stroke looks better.

**Comment by kupiqu** [comment] 2019-11-27 18:36
@trmdi could you please check if this commit 9d44fe1 helps?

**Comment by kupiqu** [comment] 2019-11-27 18:40
I have the feeling that the darker outer ring looks better but the lighter outer ring needs improvement :/

**Comment by trmdi** [comment] 2019-11-28 13:36
The lighter outer ring is the one when the titlebar is dark, isn't it? I think it looks better.
The darker one need improvement. :|

**Comment by kupiqu** [comment] 2019-11-28 13:38
> The lighter outer ring is the one when the titlebar is dark, isn't it? I think it looks better.
> The darker one need improvement. :|

Mmm, it seems like we have opposite views :D

**Comment by arun54321** [comment] 2019-11-28 16:26
![image](https://user-images.githubusercontent.com/42943340/69821413-928e9b80-1229-11ea-913c-a5929ff36843.png)
Except those button colors, the new release looks exactly like mac-os.

**Comment by kupiqu** [comment] 2019-11-28 16:31
You mean the filling or the outline?

**Comment by kupiqu** [comment] 2019-11-28 16:32
The filling was taking from macOS Catalina according to @trmdi links

RE the outline:

It seems it should be made less dark, but the problem is with title background colors that are colored themselves :(

I guess I could control for that, but kind of tired of this... :)

**Comment by arun54321** [comment] 2019-11-28 16:51
I am not reporting bug or something. It looks good to me and looks better than MacOS.

**Comment by kupiqu** [comment] 2019-11-28 16:53
Oh I see, thank you :)

I'll then close this. @trmdi feel free to open if you feel this should be further improved...

**Closed by kupiqu** 2019-11-28 16:53 UTC
